/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AppMain: typeof import('./src/layout/components/AppMain.vue')['default']
    Breadcrumb: typeof import('./src/components/Breadcrumb/index.vue')['default']
    Copy: typeof import('./src/views/system/user/components/copy.vue')['default']
    GithubCorner: typeof import('./src/components/GithubCorner/index.vue')['default']
    Hamburger: typeof import('./src/components/Hamburger/index.vue')['default']
    IconSelect: typeof import('./src/components/IconSelect/index.vue')['default']
    Jellyfish: typeof import('./src/views/dashboard/components/jellyfish.vue')['default']
    LangSelect: typeof import('./src/components/LangSelect/index.vue')['default']
    Link: typeof import('./src/layout/components/Sidebar/Link.vue')['default']
    Logo: typeof import('./src/layout/components/Sidebar/Logo.vue')['default']
    MultiUpload: typeof import('./src/components/Upload/MultiUpload.vue')['default']
    Navbar: typeof import('./src/layout/components/Navbar.vue')['default']
    Pagination: typeof import('./src/components/Pagination/index.vue')['default']
    RightPanel: typeof import('./src/components/RightPanel/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    ScrollPane: typeof import('./src/layout/components/TagsView/ScrollPane.vue')['default']
    Settings: typeof import('./src/layout/components/Settings/index.vue')['default']
    Sidebar: typeof import('./src/layout/components/Sidebar/index.vue')['default']
    SidebarItem: typeof import('./src/layout/components/Sidebar/SidebarItem.vue')['default']
    SingleUpload: typeof import('./src/components/Upload/SingleUpload.vue')['default']
    SizeSelect: typeof import('./src/components/SizeSelect/index.vue')['default']
    SvgIcon: typeof import('./src/components/SvgIcon/index.vue')['default']
    TagInput: typeof import('./src/components/TagInput/index.vue')['default']
    TagsView: typeof import('./src/layout/components/TagsView/index.vue')['default']
    WangEditor: typeof import('./src/components/WangEditor/index.vue')['default']
  }
}
